name: Build Docker image

on:
  workflow_dispatch:
  push:
  pull_request:
permissions:
  pull-requests: write
jobs:
  review:
    if: ${{ github.event_name == 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/ollama-pr.yml@main

  docker-build:
    if: ${{ github.event_name != 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/docker-publish.yml@main
    with:
      image_name: azuretunnel
      # optional
      working_dir: .
      trigger_release: ${{ github.ref_name == 'main' }}
      gitversion: true
    secrets: inherit
